// <auto-generated />
using System;
using Cafe.Dal.Infrastructure.DBSettingsEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cafe.Dal.Infrastructure.Migrations
{
    [DbContext(typeof(BotTgContext))]
    [Migration("20240920112719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cafe.Dal.Contracts.Repositories.Bot.Models.UserDataTgDb", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("Chat_Id");

                    b.Property<double?>("Count")
                        .HasColumnType("float");

                    b.HasKey("ChatId");

                    b.ToTable("UsersDataTg", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
